services:

  ###########################################################################
  # SPARK MASTER
  ###########################################################################
  spark:
    build: ./docker/spark
    image: spark:3.5.1-py312
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-app:/opt/spark-app
    command: >
      bash -c "
        mkdir -p /opt/spark/conf &&
        echo 'spark.master spark://spark:7077' >> /opt/spark/conf/spark-defaults.conf &&
        echo 'spark.deploy.rest.enabled true' >> /opt/spark/conf/spark-defaults.conf &&
        echo 'spark.master.rest.enabled true' >> /opt/spark/conf/spark-defaults.conf &&
        /opt/spark/sbin/start-master.sh &&
        tail -f /opt/spark/logs/spark--org.apache.spark.deploy.master.Master-*.out
      "


  ###########################################################################
  # SPARK WORKER
  ###########################################################################
  spark-worker:
    image: spark:3.5.1-py312
    build: ./docker/spark
    container_name: spark-worker
    depends_on:
      - spark
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
    volumes:
      - ./spark-app:/opt/spark-app
    command: >
      bash -c "
        /opt/spark/sbin/start-worker.sh spark://spark:7077 &&
        tail -f /opt/spark/logs/spark--org.apache.spark.deploy.worker.Worker-*.out
      "

  ###########################################################################
  # APACHE AIRFLOW
  ###########################################################################
  airflow:
    build:
      context: ./docker/airflow
      dockerfile: Dockerfile
    container_name: airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/spark-app
    ports:
      - "8085:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow-data:/opt/airflow
      - ./spark-app:/opt/spark-app
    command: >
      bash -c "
        rm -f /opt/airflow/airflow-webserver.pid &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname a --lastname b --role Admin --email admin@example.com &&
        airflow webserver & airflow scheduler
      "

  ###########################################################################
  # POSTGRES (source DB)
  ###########################################################################
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sourcedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-services/postgres/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

  ###########################################################################
  # MINIO (S3-compatible storage)
  ###########################################################################
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address :9001 --compat
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  ###########################################################################
  # JUPYTER NOTEBOOK (with PySpark)
  ###########################################################################
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    environment:
      - JUPYTER_TOKEN=local
    ports:
      - "8888:8888"
    volumes:
      - ./spark-app/notebooks:/home/jovyan/work

###########################################################################
# VOLUMES
###########################################################################
volumes:
  pgdata:
  minio-data:
  airflow-data: